version: '3.7'
services:
  mysql:
    image: mysql
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ./sql_volume:/var/lib/mysql
      - ./init.sql:/data/application/init.sql

